mysql:
  source:
    driverName: mysql
    host: 127.0.0.1
    port: 3306
    database: db_tiktok
    username: root
    password: 123456
    charset: utf8mb4

redis:
  addr: 127.0.0.1
  port: 6379
  db: 0