Global:
  Source: "config(local)"
  ChangeMe: "v3"

Minio:
  Endpoint: 127.0.0.1:9000
  AccessKeyId: minioadmin
  SecretAccessKey: minioadmin
  UseSSL: false
  VideoBucketName: tiktok-videos
  CoverBucketName: tiktok-video-covers
  AvatarBucketName: tiktok-user-avatars
  BackgroundImageBucketName: tiktok-user-backgrounds
  ExpireTime: 3600 # 视频临时链接过期秒数
