version: "3"
services:
  mysql:
    image: 'mysql:latest'
    restart: always
    container_name: tt-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "root"

  redis:
    image: 'redis:latest'
    restart: always
    container_name: tt-redis
    volumes:
      - ./redis/data:/data
#      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf # 先新建redis.conf文件再挂载，可从http://www.redis.cn/下载
#      - ./redis/logs:/logs
    ports:
      - '6379:6379'

  minio:
    image: 'minio/minio'
    container_name: tt-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./minio/data1:/data1"
      - "./minio/data2:/data2"
    command: server --console-address ":9001" http://minio/data{1...2}
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"

